# Generated by Django 3.2 on 2022-12-20 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Контент')),
                ('date', models.DateField(verbose_name='Дата')),
                ('img1', models.ImageField(upload_to='static/media/', verbose_name='Фотография')),
                ('img3', models.ImageField(upload_to='static/media/', verbose_name='Фотография')),
                ('img2', models.ImageField(upload_to='static/media/', verbose_name='Фотография')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.rubrics')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('-title',),
            },
        ),
    ]
