# Generated by Django 4.1 on 2022-12-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='price',
            field=models.CharField(blank=True, max_length=100, verbose_name='Цена'),
        ),
    ]
